"""add bandwidth tracking columns to interfaces

Revision ID: ff623cb8aa86
Revises: a4973e826ff0
Create Date: 2026-07-11 10:33:35.197496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff623cb8aa86'
down_revision: Union[str, None] = '772e5d0d4ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfaces', sa.Column('last_in_octets', sa.BigInteger(), nullable=True))
    op.add_column('interfaces', sa.Column('last_out_octets', sa.BigInteger(), nullable=True))
    op.add_column('interfaces', sa.Column('last_octets_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interfaces', 'last_octets_at')
    op.drop_column('interfaces', 'last_out_octets')
    op.drop_column('interfaces', 'last_in_octets')
    # ### end Alembic commands ###
